replicaCount: 1

image:
  repository: ubiviushub/microservice-template
  tag: 0.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

readinessProbe:
  httpGet:
    path: /health/ready
    port: 9090

livenessProbe:
  httpGet:
    path: /health/live 
    port: 9090
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

env:
  - name: DB_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: mongodb
        key: hostname
  - name: DB_PORT
    valueFrom:
      configMapKeyRef:
        name: mongodb
        key: port
  - name: DB_USERNAME
    valueFrom:
      configMapKeyRef:
        name: mongodb
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb
        key: mongodb-root-password

# Whether Role Based Access Control objects like roles and rolebindings should be created
rbac:
  enabled: true

  # If set to false, installs ClusterRole and ClusterRoleBinding so microservice-template can be used across namespaces.
  # If set to true, installs namespace-specific Role and RoleBinding and requires provider configuration be set to that same namespace
  namespaced: false

# Enable to create a PodSecurityPolicy and assign it to the Service Account via RoleBindin or ClusterRoleBinding
podSecurityPolicy:
  enabled: false

serviceAccount:
 # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
