{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "microservice-template.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: {{ .Values.ingressRoute.match }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          kind: Service
          port: {{ .Values.service.port }}
          namespace: {{ .Release.Namespace }}
    {{- if .Values.ingressRoute.middlewares }}
      middlewares:
      {{- range .Values.ingressRoute.middlewares }}
        - name: {{ .name }}
          namespace: default
      {{- end }}
    {{- end }}
  tls:
    secretName: {{ .Values.ingressRoute.tls.secretName }}
{{- end }}     
