name: CI

on:
  push:
    tags:
      - v*
    branches: [ master, main, feature/UBI-201-Add-push-2-dockerhub]
  pull_request:
    branches: [ master, main ]

env:
  BUILD_LVL: test
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_EMAIL: ${{ secrets.DOCKERHUB_EMAIL }}
  DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
  REPO_NAME: $GITHUB_REPOSITORY.split("/")[1]
  REPO_VERSION: 0.0.0

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  
  publish-docker:
    needs: [ build-and-test, golangci-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Artefact to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          BUILD_TYPE: $BUILD_LVL
        with:
          name: ubivius/$REPO_NAME
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          buildargs: BUILD_TYPE
          default_branch: $GITHUB_REF
          dockerfile: Dockerfile
          tags: "$REPO_VERSION"
          
