name: CI for Pull-Request on master/main

on:
  pull_request:
    branches: [ master, main ]

env:
  GIT_USER: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GITHUB_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUBCLI_TOKEN }}

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Unit tests
      run: go test -short -v ./...

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Integration tests
      run: |
        printf "pulling image for MongoDB... \n\n"
        docker pull mongo
        printf "running container... \n\n"
        docker run -d --name local-mongo -p 27888:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=pass mongo
        go test ./... -run Integration

  pr-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(major|minor|patch)\/(feature|hotfix)\/(UBI)-([0-9]{3})-([A-Za-z-]+)$' # e.g. "major|minor|patch/{{branch name}}"
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the branch name
          max_length: 60 # Max length of the branch name
          github_token: ${{ env.GITHUB_TOKEN }}
  
  convert-ingress-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Git
      run: |
          export GH_TOKEN=${{ env.GH_TOKEN }}
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          chmod 700 ./.github/main_conversion.sh
    
    - name: Change and Commit ingress prod uri paths
      run: |
          ./.github/main_conversion.sh
          git add .;
          git commit -m "Fix prod uri paths";
          git push;
